export class Project {
    advertiserName:string;
    advertisingAmount:number;
    capital:number;
    click:number;
    code:string;
    cost:number;
    ctr:number;
    ecpc:number;
    ecpm:number;
    id:number;
    impression:number;
    industryId:number;
    industryName:string;
    name:string;
    totalAmount:number;
    advertiserId:number;
    endDate:number;
    startDate:number;
}